# Generated by Django 5.2.4 on 2025-10-08 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=255)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('numero_documento', models.BigIntegerField(unique=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sedes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'tipo_documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Novedad',
                'verbose_name_plural': 'Tipos de Novedades',
                'db_table': 'tipos_novedades',
            },
        ),
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('miembros', models.ManyToManyField(related_name='grupos', to='control.empleado')),
            ],
            options={
                'verbose_name': 'Grupo de Trabajo',
                'verbose_name_plural': 'Grupos de Trabajo',
                'db_table': 'grupos_trabajo',
            },
        ),
        migrations.CreateModel(
            name='CorreoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, verbose_name='Correo Institucional')),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.empleado')),
            ],
            options={
                'verbose_name': 'Correo Institucional',
                'verbose_name_plural': 'Correo Institucionales',
                'db_table': 'correos_institucionales',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('miembros', models.ManyToManyField(related_name='horarios', to='control.empleado')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_registro', models.CharField(help_text='Entrada o Salida', max_length=20, verbose_name='Descripción')),
                ('fecha_hora_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('minutos', models.IntegerField(blank=True, null=True)),
                ('estado_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.empleado')),
                ('lugar_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.sede')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencias',
                'db_table': 'registros_asistencia',
            },
        ),
        migrations.CreateModel(
            name='NovedadAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.empleado')),
                ('fk_tipo_novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.tiponovedad')),
            ],
            options={
                'verbose_name': 'Novedad de Asistencia',
                'verbose_name_plural': 'Novedades de Asistencia',
                'db_table': 'novedades_asistencia',
            },
        ),
    ]
