# Generated by Django 5.2.4 on 2025-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='estado_registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='registro_atraso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='registro_salida_anticipada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='descripcion_registro',
            field=models.CharField(help_text='Entrada o Salida', max_length=20, verbose_name='Descripción'),
        ),
    ]
