# Generated by Django 5.2.4 on 2025-09-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_registroasistencia_estado_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroasistencia',
            old_name='registro_atraso',
            new_name='minutos',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='registro_salida_anticipada',
        ),
    ]
