# Generated by Django 5.2.4 on 2025-09-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_rename_registro_atraso_registroasistencia_minutos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
